pipeline {
    agent any

    stages {
        stage ('Unit Tests') {
            parallel {
                stage('Unit Tests - Backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-backend'){
                            sh '''
                                # Set Go cache to a writable location
                                export GOCACHE="$PWD/.cache/go-build"
                                export GOMODCACHE="$PWD/.cache/go-mod"

                                # Create cache directories
                                mkdir -p "$GOCACHE" "$GOMODCACHE"

                                # Run tests and produce test result report
                                go test -v ./... 2>&1 | go-junit-report > test-results.xml

                                # Generate coverage report
                                go test -coverprofile=coverage.out -covermode=atomic ./...
                                go tool cover -html=coverage.out -o coverage.html

                                # Create reports directory and move coverage report here
                                mkdir -p reports
                                mv coverage.html reports/
                            '''
                        }
                    }
                    post {
                        always {
                            junit 'bugtracker-backend/test-results.xml'
                            publishHTML target: [
                                reportName: 'Backend Coverage Report',
                                reportDir: 'bugtracker-backend/reports',
                                reportFiles: 'coverage.html',
                            ]
                        }
                    }
                }

                stage('Unit Tests - Frontend') {
                    agent {
                        docker {
                            image 'node:20-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-frontend'){
                            sh '''
                                # Install dependencies
                                npm ci

                                # Run tests
                                npm test

                                # Create directory for coverage report and move it there
                                mkdir -p reports
                                mv coverage reports/
                            '''
                        }
                    }
                    post {
                        always {
                            junit 'bugtracker-frontend/test-results.xml'
                            publishHTML target: [
                                reportName: 'Frontend Coverage Report',
                                reportDir: 'bugtracker-frontend/reports/coverage',
                                reportFiles: 'index.html',
                            ]
                        }
                    }
                }
            }
        }

        stage ('Launch Application') {
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps {
                //Build and run the application
                sh 'docker compose up -d --build'
            }
        }

        stage ('Playwright Tests'){
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.50.0-jammy'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            stage('Setup'){
                steps {
                    // Wait for docker to be ready
                    sh 'npx wait-port http://localhost:8080/api/health -t 30000'
                }
            }
            parallel {
                stage('API Tests') {
                    steps {
                        dir('bugtracker/tests-api') {
                            sh 'npm ci && npx playwright test --reporter=html'
                        }
                    }
                    post {
                        always {
                            publishHTML target: [
                                reportName: 'API Test Results',
                                reportDir: 'bugtracker/tests-api/playwright-report',
                                reportFiles: 'index.html',
                            ]
                        }
                    }
                },
                stage('E2E Tests') {
                    steps {
                        dir('bugtracker/tests-e2e') {
                            sh 'npm ci && npx playwright test --reporter=html'
                        }
                    }
                    post {
                        always {
                            publishHTML target: [
                                reportName: 'E2E Test Results',
                                reportDir: 'bugtracker/tests-e2e/playwright-report',
                                reportFiles: 'index.html',
                            ]
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs() // Clean workspace after all the stages have finished running
        }
    }
}
