name: CI

on:
  push:
    branches: 
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

jobs:
    unit-tests-backend:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: bugtracker-backend
        outputs:
            coverage: ${{ steps.coverage-report-backend.outputs.report }}
        steps:
            - uses: actions/checkout@v5 # Check out the repository

            - name: Set up Go
              uses: actions/setup-go@v6 # Github special actions to help install Go onto Github runner instance
              with:
                go-version: '1.25' # Specify the Go version
                cache-dependency-path: ./bugtracker-backend/go.sum # Cache the files so that it is reused in subsequent runs
            
            - name: Install go-junit-report
              run: go install github.com/jstemmer/go-junit-report/v2@latest

            - name: Backend Code Coverage Report
              id: coverage-report-backend
              run: |

                go test -json -coverprofile=coverage.out -covermode=atomic ./...
                go tool cover -func=coverage.out > coverage.txt

                # Displays the coverage report directly on the GitHub Actions workflow page
                echo "## 📊 Backend Test Coverage Report" >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY
                cat coverage.txt >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY

                # Save coverage report as an output to be used to create PR comment
                echo 'report<<EOF' >> $GITHUB_OUTPUT
                cat coverage.txt >> $GITHUB_OUTPUT
                echo 'EOF' >> $GITHUB_OUTPUT

            - name: Run Backend Unit Tests
              run: |

                go test -v ./... 2>&1 | go-junit-report > test-results.xml

            - name: Publish Backend Unit Tests Result
              uses: dorny/test-reporter@v1
              if: always()
              with:
                name: Backend Unit Tests Result
                path: ./bugtracker-backend/test-results.xml
                reporter: jest-junit

    unit-tests-frontend:
        runs-on: ubuntu-latest
        outputs:
            coverage: ${{ steps.run-tests-frontend.outputs.report }}
        steps:
            - uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '24' 
                cache: 'npm'
                cache-dependency-path: ./bugtracker-frontend/package-lock.json
                
            - name: Run Frontend Unit Tests
              id: run-tests-frontend
              working-directory: ./bugtracker-frontend
              run: |

                npm ci
                npm test | tee full_output.txt
                
                echo '## 📊 Frontend Test Coverage Report' >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY
                cat full_output.txt >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY

                # Save coverage report as an output to be used to create PR comment
                echo 'report<<EOF' >> $GITHUB_OUTPUT
                cat full_output.txt >> $GITHUB_OUTPUT
                echo 'EOF' >> $GITHUB_OUTPUT

            - name: Publish Frontend Unit Tests Result
              uses: dorny/test-reporter@v1
              if: always()
              with:
                name: Frontend Unit Tests Result
                path: ./bugtracker-frontend/test-results.xml
                reporter: jest-junit

    create-coverage-comment:
      if: github.event_name == 'pull_request'
      needs: [unit-tests-backend, unit-tests-frontend]
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      steps:
        - name: Create Backend Coverage Comment
          uses: peter-evans/create-or-update-comment@v4
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              ## 📊 Backend Test Coverage Report
              ```
              ${{ needs.unit-tests-backend.outputs.coverage }}
              ```
        - name: Create Frontend Coverage Comment
          uses: peter-evans/create-or-update-comment@v4
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              ## 📊 Frontend Test Coverage Report
              ```
              ${{ needs.unit-tests-frontend.outputs.coverage }}

    deploy:
        if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' }}
        needs: [unit-tests-backend, unit-tests-frontend]
        environment:  ${{ github.ref_name == 'main' || 'staging' }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: |
                DEPLOY_HOOK_URL=$1
                SERVICE_ID=$2
                SERVICE_NAME=$3
                
                deploy_and_wait() {
                  echo "🚀 Deploying to staging environment..."
                  DEPLOY_ID=$(curl "$DEPLOY_HOOK_URL" | jq -r '.deploy.id')

                  if [ -z "$DEPLOY_ID" ] || [ "$DEPLOY_ID" = "null" ]; then
                      echo "No deploy ID returned"
                      exit 1
                  fi
                  
                  echo "⏱️Polling status of deployment $SERVICE_NAME"

                  i=1
                  while [ "$i" -le 40 ]; do
                      STATUS=$(curl -sS --fail \
                      --request GET \
                      --url "https://api.render.com/v1/services/$SERVICE_ID/deploys/$DEPLOY_ID" \
                      --header "Authorization: Bearer $RENDER_API_KEY" \
                      | jq -r '.status')

                      echo "$SERVICE_NAME deployment status: $STATUS"
                      if [ "$STATUS" = "live" ]; then
                          echo "✅ $SERVICE_NAME deployment is live! 🎉"
                          return 0
                      fi

                      case "$STATUS" in
                      *"failed"*|*"canceled"*|*"deactivated"*)
                          echo "❌ $SERVICE_NAME deployment failed with status: $STATUS"
                          exit 1
                          ;;
                      esac

                      sleep 5
                      i=$((i + 1))
                  done

                  echo "$SERVICE_NAME deployment did not become live within expected time"
                  exit 1
                }
                
                deploy_and_wait \
                "$backend_staging_deploy" \
                "$backend_staging_service_id" \
                "bugtracker-backend-staging-kamui"

                deploy_and_wait \
                "$frontend_staging_deploy" \
                "$frontend_staging_serviceid" \
                "bugtracker-frontend-staging-kamui"

    smoke-tests:
        if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' }}
        environment:  ${{ github.ref_name == 'main' || 'staging' }}
        needs: [deploy]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Run API Tests
              working-directory: ./tests-api
              run: npm ci && npx playwright test

            - name: Upload API Test Results
              if: always()
              uses: actions/upload-artifact@v6
              with:
                name: api-test-results
                path: ./tests-api/test-results/
                retention-days: 30

            - name: Upload API Test Playwright Report
              if: always()
              uses: actions/upload-artifact@v6
              with:
                name: api-test-playwright-report
                path: ./tests-api/playwright-report/
                retention-days: 30

    regression-tests:
        needs: [smoke-tests]
        if: github.ref_name == 'main' || github.ref_name == 'staging'
        environment: ${{ github.ref_name == 'main' || 'staging' }}
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5

          - name: Run E2E Tests
            env:
              APP_URL: ${{ secrets.APP_BASE_URL }}
            working-directory: ./tests-e2e
            run: |
              npm ci
              npx playwright install
              npx playwright test

          - name: Upload E2E Test Results
            if: always()
            uses: actions/upload-artifact@v6
            with:
              name: e2e-test-results
              path: ./tests-e2e/test-results/
              retention-days: 30

          - name: Upload E2E Test Playwright Report
            if: always()
            uses: actions/upload-artifact@v6
            with:
              name: e2e-test-playwright-report
              path: ./tests-e2e/playwright-report/
              retention-days: 30

          - name: Publish API Test Results
            uses: dorny/test-reporter@v1
            if: always()
            with:
              name: Playwright API Test Results
              path: ./tests-api/test-results/*.xml
              reporter: jest-junit
          
          - name: Publish E2E Test Results
            uses: dorny/test-reporter@v1
            if: always()
            with:
              name: Playwright E2E Test Results
              path: ./tests-e2e/test-results/*.xml
              reporter: jest-junit

    performance-tests:
        if: ${{ github.ref_name == 'staging' }}
        needs: [regression-tests]
        permissions:
          pages: write
          id-token: write
          contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Launch App
              run: |
                export DATABASE_URL="$TEST_DATABASE_URL"
                if [ -z "$DATABASE_URL" ]; then
                  echo "DATABASE_URL is empty"
                  exit 1
                fi
                docker compose up --build -d
                docker compose logs
                npx wait-port http://localhost:8080/api/health -t 30000

            - name: Set up k6
              uses: grafana/setup-k6-action@v1
            
            - name: Run Performance tests
              uses: grafana/run-k6-action@v1
              with:
                path: ./tests-perf/script.js
                flags: --out json=summary.json
    
            - name: Tear down App
              run: docker compose down

            - name: Prepare Pages site
              if: always()
              run: |
                mkdir -p site
                cp perf-results.html site/index.html
            
            - name: Upload Performance Raw Results
              if: always()
              uses: actions/upload-artifact@v6
              with:
                name: performance-test-raw-results
                path: summary.json
              
            - name: Upload Performance Test Report
              if: always()
              uses: actions/upload-artifact@v6
              with:
                name: performance-test-report
                path: perf-results.html

            - name: Upload Pages artifact
              if: always()
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./site

    deploy-performance-report:
        needs: [performance-tests]
        if: |
          always() &&
          github.ref_name == 'staging'
        permissions:
          pages: write
          id-token: write
        runs-on: ubuntu-latest
        environment:
          name: github-pages
          url: ${{ steps.publish-report.outputs.page_url }}

        steps:
          - name: Deploy report to GitHub Pages
            id: publish-report
            uses: actions/deploy-pages@v4