name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
    unit-tests-backend:
        runs-on: ubuntu-latest
        outputs:
            coverage: ${{ steps.coverage-report-backend.outputs.report }}
        steps:
            - uses: actions/checkout@v5 # Check out the repository

            - name: Set up Go
              uses: actions/setup-go@v6 # Github special actions to help install Go onto Github runner instance
              with:
                go-version: '1.21' # Specify the Go version
                cache-dependency-path: ./bugtracker-backend/go.sum # Cache the files so that it is reused in subsequent runs
            
            - name: Install go-junit-report
              run: go install github.com/jstemmer/go-junit-report/v2@latest

            - name: Backend Code Coverage Report
              id: coverage-report-backend
              working-directory: ./bugtracker-backend
              run: |

                go test -json -coverprofile=coverage.out -covermode=atomic ./...
                go tool cover -func=coverage.out > coverage.txt

                # Displays the coverage report directly on the GitHub Actions workflow page
                echo "## 📊 Backend Test Coverage Report" >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY
                cat coverage.txt >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY

                # Save coverage report as an output to be used to create PR comment
                echo 'report<<EOF' >> $GITHUB_OUTPUT
                cat coverage.txt >> $GITHUB_OUTPUT
                echo 'EOF' >> $GITHUB_OUTPUT

            - name: Run Backend Unit Tests
              working-directory: ./bugtracker-backend
              run: |

                go test -v ./... 2>&1 | go-junit-report > test-results.xml

            - name: Publish Backend Unit Tests Result
              uses: dorny/test-reporter@v1
              if: always()
              with:
                name: Backend Unit Tests Result
                path: ./bugtracker-backend/test-results.xml
                reporter: jest-junit

    unit-tests-frontend:
        runs-on: ubuntu-latest
        outputs:
            coverage: ${{ steps.run-test-frontend.outputs.report }}
        steps:
            - uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '24' 
                cache: 'npm'
                cache-dependency-path: ./bugtracker-frontend/package-lock.json
                
            - name: Run Frontend Unit Tests
              id: run-test-frontend
              working-directory: ./bugtracker-frontend
              run: |
                npm ci
                npm test | tee full_output.txt

            - name: Frontend Code Coverage Report
              working-directory: ./bugtracker-frontend
              run: |

                echo '## 📊 Frontend Test Coverage Report' >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY
                cat full_output.txt >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY

                # Save coverage report as an output to be used to create PR comment
                echo 'report<<EOF' >> $GITHUB_OUTPUT
                cat full_output.txt >> $GITHUB_OUTPUT
                echo 'EOF' >> $GITHUB_OUTPUT

            - name: Publish Frontend Unit Tests Result
              uses: dorny/test-reporter@v1
              if: always()
              with:
                name: Frontend Unit Tests Result
                path: ./bugtracker-frontend/test-results.xml
                reporter: jest-junit

    create-coverage-comment:
      if: github.event_name == 'pull_request'
      needs: [unit-tests-backend, unit-tests-frontend]
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      steps:
        - name: Create Backend Coverage Comment
          uses: peter-evans/create-or-update-comment@v4
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              ## 📊 Backend Test Coverage Report
              ```
              ${{ needs.unit-tests-backend.outputs.coverage }}
              ```
        - name: Create Frontend Coverage Comment
          uses: peter-evans/create-or-update-comment@v4
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              ## 📊 Frontend Test Coverage Report
              ```
              ${{ needs.unit-tests-frontend.outputs.coverage }}
              ``` 
#
#   playwright-api-tests:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v5

#            - name: Run Playwright API Tests
#              working-directory: ./tests-api
#              run: npm ci && npx playwright test
#    playwright-e2e-tests:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v5
#
#            - name: Run Playwright E2E Tests
#              working-directory: ./tests-e2e
#              run: npm ci && npx playwright test
#    k6-perf-tests:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v5
#
#            - name: Run k6 Performance tests
#              working-directory: ./tests-perf
#              run: k6 run script.js